version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - PORT=5001
    volumes:
      - ./cache:/app/cache
    restart: unless-stopped
